// This file was generated by Scene Builder
// Note that after you generate this file
//   you will need to manually update it to reflect any 
//   additions or deletions. You don't want to overwrite
//   this file once you start to put code in it.
//
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;

public class DemoViewController {

    @FXML
    private TextField myInput;

    @FXML
    private Label myLabel;

    @FXML
    void updateLabel(ActionEvent event) {
      // Get the input text and set the label 
      myLabel.setText(myInput.getText());
      // Some console output for debugging purposes
      System.out.println("Button pressed!");
    }

}
